# Use docker compose up --build to run this

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:80
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development