@url = http://localhost:5028/ecoshare/Usuarios/ResetPassword

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "Token": "CfDJ8I0wMmbXeHtIrGOR8NdoFCzyGTbOJc8R5ue6pI8NpovKhEZdwRCpKqYCRovLWP4dR3Ia+3YEBC69/0dHMLFd/kzRQks0ytEaaTZ/IgkJ+a/OmWHzzGdMIuP/YNtiz6N3/A5VulUUHpNj3wnZECtcQ3uYhO+3sTJVcqJ4MZDaTplSbQP57zWCd2MlQeKenRAGgYLhKtPnIvhckyQLFBBVATs24zCpCo9rb0pcq3zVh3zm",
    "Email": "bemesko@gmail.com",
    "NewPassword": "SenhaSuperSecreta1!",
}